### PR TITLE
fix: Only show region selector for sites with more than one partnership

### LINKED ISSUE #507: [Bug]: Region button displaying for site with one partnership
## Description

Region selection buttons display for a site with one partnership. This is unnecessary, since there are no alternative partnerships to switch between.

## Steps to reproduce

1. Update `PARTNERSHIP_TAG_LIST` in `.env` to include just one partnership, e.g:

```
PARTNERSHIP_TAG_LIST=35|Fruit Salad Events
```

2. Observe that buttons for this region and 'Everywhere' are displayed on the `/events` and `/partners` pages:

Image

## Suggested fix

Only render the region selector if the `PARTNERSHIP_TAG_LIST` length is greater than 1.

### PR DESCRIPTION
**Pull request by james-collapse**
Fixes #507

## Description

- Shows region selector for sites with more than one partnership, hides otherwise

Tested using `PARTNERSHIP_TAG_LIST=3|London`:

Screenshot 2025-01-28 at 14 56 41

Screenshot 2025-01-28 at 14 56 53

### CODE REVIEW

File: src/Theme/RegionSelector.elm [hunk 1]
```diff
@@ -2,10 +2,10 @@ module Theme.RegionSelector exposing (Msg(..), viewRegionSelector)
 
 import Copy.Keys exposing (Key(..))
 import Copy.Text exposing (t)
-import Css exposing (Style, active, auto, backgroundColor, batch, borderBox, borderColor, borderRadius, borderStyle, borderWidth, boxSizing, center, color, cursor, displayFlex, fitContent, flexWrap, focus, fontSize, fontWeight, hover, int, justifyContent, listStyleType, margin2, margin4, maxWidth, none, padding4, pointer, position, property, px, relative, rem, solid, textAlign, width, wrap)
+import Css exposing (Style, active, auto, backgroundColor, batch, borderBox, borderColor, borderRadius, borderStyle, borderWidth, boxSizing, center, color, cursor, display, displayFlex, fitContent, flexWrap, focus, fontSize, fontWeight, hover, int, justifyContent, listStyleType, margin2, margin4, maxWidth, none, padding4, pointer, position, property, px, relative, rem, solid, textAlign, width, wrap)
 import Css.Global exposing (descendants, typeSelector)
 import Css.Transitions exposing (transition)
-import Data.PlaceCal.Partners
+import Data.PlaceCal.Partners exposing (partnershipTagList)
```
Comment (katjam) [inline src/Theme/RegionSelector.elm:8]: We've been fully qualifying calls instead of exposing to make it more obvious where the code comes from on the line it's used.

e.g. call the function on line 98 with `Data.PlaceCal.Partners.partnershipTagList` and remove the exposing clause.

File: src/Theme/RegionSelector.elm [hunk 2]
```diff
@@ -95,11 +95,15 @@ buttonMarginFullWidth =
...
-        ]
+    if List.length partnershipTagList > 1 then
+        batch
+            [ margin2 (rem 0) (rem -0.5)
+            , withMediaSmallDesktopUp [ margin4 (rem 2) (rem -1) (rem 3) (rem -1) ]
+            , withMediaTabletLandscapeUp [ margin2 (rem 2) (rem -1) ]
+            ]
+
+    else
+        display none
```
Comment (katjam) [inline src/Theme/RegionSelector.elm:106]: This works but it might be better to not output the region selector component at all in the html logic.

If you tried that and it got complicated then I'll approve this.

Comment (james-collapse) [reply src/Theme/RegionSelector.elm:106]: It's not too complicated, it's just a bit more work updating Events, Index and Partners - happy to do that instead.

File: src/Theme/Page/Events.elm [hunk 3]
```diff
@@ -43,11 +44,17 @@ viewEvents :
...
+        if List.length Data.PlaceCal.Partners.partnershipTagList > 1 then
+            [ Theme.RegionSelector.viewRegionSelector { filterBy = model.filterByRegion } |> Html.Styled.map fromRegionSelectorMsg
+            , Theme.Paginator.viewPagination model |> Html.Styled.map fromPaginatorMsg
+            , viewEventsList model eventsList Nothing
+            ]
+
+        else
+            [ Theme.Paginator.viewPagination model |> Html.Styled.map fromPaginatorMsg
+            , viewEventsList model eventsList Nothing
+            ]
```
Comment (mateusfpleite) [inline src/Theme/Page/Events.elm:57]: I think it would be better to render the regionSelector conditionally rather than creating a separate list for each case. That way, if we ever need to add another item to the list in the future, we won’t risk forgetting to update one of the separate cases. It might look something like this:

```suggestion
    section [ css [ eventsContainerStyle ] ]
        [ if List.length Data.PlaceCal.Partners.partnershipTagList > 1 then
            Theme.RegionSelector.viewRegionSelector { filterBy = model.filterByRegion } |> Html.Styled.map fromRegionSelectorMsg

          else
            text ""
        , Theme.Paginator.viewPagination model |> Html.Styled.map fromPaginatorMsg
        , viewEventsList model eventsList Nothing
        ]
```
  
 The same applies to `Index` and `Partners`.

Comment (james-collapse) [reply src/Theme/Page/Events.elm:57]: Thanks @mateusfpleite - I wasn't sure how to create an empty HTML node, but if that works I'm happy to change it.

Comment (mateusfpleite) [reply src/Theme/Page/Events.elm]: @james-collapse yeah, It would be nice if the standart HTML module had a more explicit way to represent empty HTMlL, like [nothing](https://package.elm-lang.org/packages/elm-community/html-extra/latest/Html-Extra#nothing) in `HTML.Extra`

**Review by mateusfpleite — APPROVED** [review]
LGTM!
