### PR TITLE
fix: add summary to partner show pages

### LINKED ISSUE #433: [Bug]: Partner pages not showing partner summaries
## Description

I was looking at a trans meetup group and thought it strange it said to ask for more information when that information does exist on PlaceCal.

On looking further it seems partner pages only show "description" text and not "summary" text.

View on Trans Dim:

Screenshot 2024-09-07 at 18 31 06

View on PlaceCal:

Screenshot 2024-09-07 at 18 31 58

Evidence that this info is on Trans Dim, just not being used:

Screenshot 2024-09-07 at 18 32 42

I think this is a serious bug as the summary is the most important part of the partner description and this implies they don't have one.

## Desired behaviour

Partner pages show the summary above the description text, possibly in a larger font size to match PlaceCal.

### PR DESCRIPTION
**Pull request by kimadactyl**
Fixes #433

## Description

Shows summary and description on show pages.

Note that this bug existing has resulted in people improvising in the backend repeating info - example below. We may need to do some post-fix cleanup.

Screenshot 2024-11-20 at 16 24 23

Screenshot showing change vs original bug ticket:

Screenshot 2024-11-20 at 16 29 39

<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNlMGQ2M2U3Y2M1YTc4NTQyZTVlN2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.cnX74TV1oKygD20MDP1CW0K_oxUE0PLOAI1e1uhNxdo">Huly&reg;: <b>TD-458</b></a></sub>

### CODE REVIEW

**Comment by kimadactyl** [comment]
A bit out my depth here but thought I'd give it a crack!

File: src/Theme/Page/Partner.elm [hunk 1]
```diff
@@ -2,7 +2,7 @@ module Theme.Page.Partner exposing (viewInfo)
 
 import Copy.Keys exposing (Key(..))
 import Copy.Text exposing (t)
-import Css exposing (Style, auto, batch, calc, center, color, displayFlex, fontStyle, important, margin2, margin4, marginBlockEnd, marginBlockStart, marginTop, maxWidth, minus, normal, pct, px, rem, textAlign, width)
+import Css exposing (Style, auto, batch, calc, center, color, displayFlex, fontStyle, important, margin2, margin4, marginBlockEnd, marginBlockStart, marginTop, maxWidth, minus, normal, pct, px, rem, textAlign, text_, width)
```
Comment (katjam) [inline src/Theme/Page/Partner.elm:5]: I don't think you ended up using this `text_` import

File: src/Theme/Page/Partner.elm [hunk 2]
```diff
@@ -15,7 +15,13 @@ import Theme.TransMarkdown
 viewInfo localModel { partner, events } =
     section [ css [ margin2 (rem 0) (rem 0.35) ] ]
         [ text ""
-        , div [ css [ descriptionStyle ] ] (Theme.TransMarkdown.markdownToHtml (t (PartnerDescriptionText partner.description partner.name)))
+        , div [ css [ descriptionStyle ] ]
+            (Theme.TransMarkdown.markdownToHtml
+                (t (PartnerDescriptionText partner.summary partner.name)
+                    ++ "\n\n"
```
Comment (katjam) [inline src/Theme/Page/Partner.elm:21]: I think instead of the manual newline between the 2 sections of text, we could copy the whole thing and make  2 divs - depends what styles we want to apply to both but we might want the `descriptionStyle` css to wrap both.

We also probably only want the "Ask partner for more information" to show for one or other. I guess leave it on the description? I think maybe this site was designed with the summary being used in the list and the description being used in this page so we might even want more logic to check if they repeat each other or only show empty text if both are empty?

It would be more clear if that logic to show empty text was here instead of in the translation file.

Try something like:
```
, div [ css [ descriptionStyle ] ] 
    [ div [ ] (Theme.TransMarkdown.markdownToHtml partner.summary)
    , div [ ] (Theme.TransMarkdown.markdownToHtml (t (PartnerDescriptionText partner.description partner.name)))
    ]
```
or
```
, div [ css [ descriptionStyle ] ] (Theme.TransMarkdown.markdownToHtml partner.summary)
, div [ css [ descriptionStyle ] ] (Theme.TransMarkdown.markdownToHtml (t (PartnerDescriptionText partner.description partner.name)))
```

**Review by katjam — COMMENTED** [review]
As with everything, this is a bit more complicated than it first appears, but good effort. Apart from the repeating empty test, this would appear fine to end user.

File: src/Theme/Page/Partner.elm (hunk 1 above)
Comment (kimadactyl) [reply src/Theme/Page/Partner.elm:5]: oh i think vscode must have inserted this automatically!  annoying it adds and doesn't cut

File: src/Theme/Page/Partner.elm (hunk 2 above)
Comment (kimadactyl) [reply src/Theme/Page/Partner.elm:21]: i tried this first but it adds awkward looking spacing between bc the div has padding on it too - i don't think we want the extra div?

ah i missed the no text state - i guess ideally this would be a fuction that processes the whole thing but getting a bit out my depth!

Comment (katjam) [reply src/Theme/Page/Partner.elm:21]: We can fix the styling on the divs if there is too much padding - maybe we need to make a new style and not use the existing descriptionStyle.

You're doing fine with it! And yes, I think I'm inclined to change that copy key to `PartnerDecriptionEmptyText` and then as you say, make a function here that only shows it if both summary & description are empty. Shout if you want a hand.

**Comment by katjam** [comment]
Of course. No problem. Look after yourself.

**Comment by kimadactyl** [comment]
oh are you good to get this fixed and merged too @katjam? last one :)

**Comment by katjam** [comment]
Sure. I'll release the other stuff anyway and get this done asap.

**Comment by james-collapse** [comment]
@katjam @kimadactyl think I've resolved this with my last commit - the logic is now:

* If both description and summary are empty, show `PartnerDescriptionEmptyText`
* If description is empty but summary is not, show summary
* If summary is empty but description is not, show description
* If both summary and description are present, show both.

Here's how it looks for London Transgender Meetup Group (summary only):

Screenshot 2024-12-16 at 19 48 37

Here's how it looks for Dalston Superstore (both summary and description):

Screenshot 2024-12-16 at 19 55 50

Here's how it looks for Feel Good Club (neither):

Screenshot 2024-12-16 at 19 56 35

**Comment by kimadactyl** [comment]
This sounds perfect to me and I'm happy for you to merge!

**Review by james-collapse — APPROVED** [review]
